# Generated by Django 5.0.2 on 2025-01-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product_current_price_and_more'),
        ('watchlist', '0002_watchlistitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
